name: GTFS Validation
description: Continious GTFS Data Validation
author: Elizabeth Sall
branding:
  icon: check-circle
  color: green
inputs:
  gtfs:
    description: Path to a GTFS Schedule to validate
    default: None
    required: false
  validator-version:
    description: Version of the GTFS schedule-validator. Will default to latest.
    default: latest
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.gtfs }}
    - ${{ inputs.validator-version }}
    