name: test-action

on: push

env:
  VALIDATOR_VERSION: latest
  GTFS_URL: http://gtfs.bigbluebus.com/current.zip

jobs:
  test-url:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull canonical GTFS validator, version: ${{ env.VALIDATOR_VERSION }}'
        run: docker pull ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }}
      - name: Test GTFS at URL
        run: docker run --rm ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }} -i ${{ env.GTFS_URL }} -o /tmp/gtfs-output
