name: test-action

on: push

env:
  VALIDATOR_VERSION: latest
  GTFS_EXAMPLE_PATH: examples/alhambra-ca-us.zip

jobs:
  test-url:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull canonical GTFS validator, version: ${{ env.VALIDATOR_VERSION }}'
        run: docker pull ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }}
      - uses: actions/checkout@v3
      - name: Test GTFS at URL
        run: docker run --rm ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }} -i ${{ env.GTFS_EXAMPLE_PATH }} -o /tmp/gtfs-output
