name: test-action

on: push

env:
  VALIDATOR_VERSION: latest

jobs:
  test-url:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull canonical GTFS validator, version: ${{ env.VALIDATOR_VERSION }}'
        run: docker pull ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }}
      - uses: actions/checkout@v3
      - name: Test local example feed
        run: |
          docker run \
            --rm \
            --volume "$(pwd)/examples:/gtfs" \
            ghcr.io/mobilitydata/gtfs-validator:${{ env.VALIDATOR_VERSION }} \
              -i /gtfs/alhambra-ca-us.zip \
              -o /gtfs/validator-output
      - uses: actions/upload-artifact@v3
        with:
          name: validator-output
          path: ./validator-output/
